export { activeLineIndex, parseLrc } from './lrc'
export type { LyricLine } from './lrc'
export { fetchLyrics } from './provider'
export type { LyricsQuery } from './provider'
export { useLyrics } from './use-lyrics'
export type { LyricsState, LyricsStatus } from './use-lyrics'
